/* class-mp3-player.c generated by valac, the Vala compiler
 * generated from class-mp3-player.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <OMX_Core.h>
#include <OMX_Component.h>


#define TYPE_MP3_PLAYER (mp3_player_get_type ())
#define MP3_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MP3_PLAYER, Mp3Player))
#define MP3_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MP3_PLAYER, Mp3PlayerClass))
#define IS_MP3_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MP3_PLAYER))
#define IS_MP3_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MP3_PLAYER))
#define MP3_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MP3_PLAYER, Mp3PlayerClass))

typedef struct _Mp3Player Mp3Player;
typedef struct _Mp3PlayerClass Mp3PlayerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _Mp3PlayerPrivate Mp3PlayerPrivate;
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))

#define OMX_TYPE_COMPONENT (omx_component_get_type ())
#define OMX_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMX_TYPE_COMPONENT, OmxComponent))
#define OMX_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMX_TYPE_COMPONENT, OmxComponentClass))
#define OMX_IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMX_TYPE_COMPONENT))
#define OMX_IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMX_TYPE_COMPONENT))
#define OMX_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMX_TYPE_COMPONENT, OmxComponentClass))

typedef struct _OmxComponent OmxComponent;
typedef struct _OmxComponentClass OmxComponentClass;

#define OMX_TYPE_PORT (omx_port_get_type ())
#define OMX_PORT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMX_TYPE_PORT, OmxPort))
#define OMX_PORT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMX_TYPE_PORT, OmxPortClass))
#define OMX_IS_PORT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMX_TYPE_PORT))
#define OMX_IS_PORT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMX_TYPE_PORT))
#define OMX_PORT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMX_TYPE_PORT, OmxPortClass))

typedef struct _OmxPort OmxPort;
typedef struct _OmxPortClass OmxPortClass;
typedef struct _OmxPortPrivate OmxPortPrivate;

struct _Mp3Player {
	GObject parent_instance;
	Mp3PlayerPrivate * priv;
};

struct _Mp3PlayerClass {
	GObjectClass parent_class;
};

struct _OmxPort {
	GObject parent_instance;
	OmxPortPrivate * priv;
	OMX_PARAM_PORTDEFINITIONTYPE definition;
	OMX_BUFFERHEADERTYPE** buffers;
	gint buffers_length1;
	GAsyncQueue* buffer_queue;
	OmxComponent* component;
};

struct _OmxPortClass {
	GObjectClass parent_class;
};


static gpointer mp3_player_parent_class = NULL;

Mp3Player* mp3_player_new (void);
Mp3Player* mp3_player_construct (GType object_type);
GType mp3_player_get_type (void);
void mp3_player_play (Mp3Player* self, const char* filename, GError** error);
gint _main (char** args, int args_length1);
enum  {
	MP3_PLAYER_DUMMY_PROPERTY
};
#define MP3_PLAYER_AUDIODEC_COMPONENT_NAME "OMX.st.audio_decoder.mp3.mad"
OmxComponent* omx_component_new (const char* component_name, OMX_INDEXTYPE param_init_index);
OmxComponent* omx_component_construct (GType object_type, const char* component_name, OMX_INDEXTYPE param_init_index);
GType omx_component_get_type (void);
void omx_component_set_name (OmxComponent* self, const char* value);
void omx_component_init (OmxComponent* self, GError** error);
void omx_component_set_state (OmxComponent* self, OMX_STATETYPE state, GError** error);
void omx_component_allocate_ports (OmxComponent* self, GError** error);
void omx_component_wait_for_state_set (OmxComponent* self);
void omx_component_fill_output_buffers (OmxComponent* self, GError** error);
void omx_component_empty_input_buffers (OmxComponent* self, GError** error);
GType omx_port_get_type (void);
OmxPort* omx_component_pop_port (OmxComponent* self);
OMX_BUFFERHEADERTYPE* omx_port_pop_buffer (OmxPort* self);
void omx_port_push_buffer (OmxPort* self, OMX_BUFFERHEADERTYPE* buffer, GError** error);
void omx_component_free_ports (OmxComponent* self, GError** error);
void omx_component_free (OmxComponent* self, GError** error);



gint _main (char** args, int args_length1) {
	gint result;
	GError * _inner_error_;
	Mp3Player* player;
	_inner_error_ = NULL;
	if (args_length1 != 2) {
		g_print ("%s <file.mp3>\n", args[0]);
		result = 1;
		return result;
	}
	player = mp3_player_new ();
	{
		mp3_player_play (player, args[1], &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		result = 0;
		_g_object_unref0 (player);
		return result;
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_print ("%s\n", e->message);
			result = 1;
			_g_error_free0 (e);
			_g_object_unref0 (player);
			return result;
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (player);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_g_object_unref0 (player);
}


int main (int argc, char ** argv) {
	g_thread_init (NULL);
	g_type_init ();
	return _main (argv, argc);
}


static GQuark omx_error_domain (void) {
	GQuark result;
	result = g_quark_from_string ("Omx.Error");
	return result;
}


static const char* omx_error_to_string (OMX_ERRORTYPE self) {
	const char* result;
	switch (self) {
		case OMX_ErrorNone:
		{
			result = "Omx.Error.None";
			return result;
		}
		case OMX_ErrorInsufficientResources:
		{
			result = "Omx.Error.InsufficientResources";
			return result;
		}
		case OMX_ErrorUndefined:
		{
			result = "Omx.Error.Undefined";
			return result;
		}
		case OMX_ErrorInvalidComponentName:
		{
			result = "Omx.Error.InvalidComponentName";
			return result;
		}
		case OMX_ErrorComponentNotFound:
		{
			result = "Omx.Error.ComponentNotFound";
			return result;
		}
		case OMX_ErrorInvalidComponent:
		{
			result = "Omx.Error.InvalidComponent";
			return result;
		}
		case OMX_ErrorBadParameter:
		{
			result = "Omx.Error.BadParameter";
			return result;
		}
		case OMX_ErrorNotImplemented:
		{
			result = "Omx.Error.NotImplemented";
			return result;
		}
		case OMX_ErrorUnderflow:
		{
			result = "Omx.Error.Underflow";
			return result;
		}
		case OMX_ErrorOverflow:
		{
			result = "Omx.Error.Overflow";
			return result;
		}
		case OMX_ErrorHardware:
		{
			result = "Omx.Error.Hardware";
			return result;
		}
		case OMX_ErrorInvalidState:
		{
			result = "Omx.Error.InvalidState";
			return result;
		}
		case OMX_ErrorStreamCorrupt:
		{
			result = "Omx.Error.StreamCorrupt";
			return result;
		}
		case OMX_ErrorPortsNotCompatible:
		{
			result = "Omx.Error.PortsNotCompatible";
			return result;
		}
		case OMX_ErrorResourcesLost:
		{
			result = "Omx.Error.ResourcesLost";
			return result;
		}
		case OMX_ErrorNoMore:
		{
			result = "Omx.Error.NoMore";
			return result;
		}
		case OMX_ErrorVersionMismatch:
		{
			result = "Omx.Error.VersionMismatch";
			return result;
		}
		case OMX_ErrorNotReady:
		{
			result = "Omx.Error.NotReady";
			return result;
		}
		case OMX_ErrorTimeout:
		{
			result = "Omx.Error.Timeout";
			return result;
		}
		case OMX_ErrorSameState:
		{
			result = "Omx.Error.SameState";
			return result;
		}
		case OMX_ErrorResourcesPreempted:
		{
			result = "Omx.Error.ResourcesPreempted";
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringAllocation:
		{
			result = "Omx.Error.PortUnresponsiveDuringAllocation";
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringDeallocation:
		{
			result = "Omx.Error.PortUnresponsiveDuringDeallocation";
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringStop:
		{
			result = "Omx.Error.PortUnresponsiveDuringStop";
			return result;
		}
		case OMX_ErrorIncorrectStateTransition:
		{
			result = "Omx.Error.IncorrectStateTransition";
			return result;
		}
		case OMX_ErrorIncorrectStateOperation:
		{
			result = "Omx.Error.IncorrectStateOperation";
			return result;
		}
		case OMX_ErrorUnsupportedSetting:
		{
			result = "Omx.Error.UnsupportedSetting";
			return result;
		}
		case OMX_ErrorUnsupportedIndex:
		{
			result = "Omx.Error.UnsupportedIndex";
			return result;
		}
		case OMX_ErrorBadPortIndex:
		{
			result = "Omx.Error.BadPortIndex";
			return result;
		}
		case OMX_ErrorPortUnpopulated:
		{
			result = "Omx.Error.PortUnpopulated";
			return result;
		}
		case OMX_ErrorComponentSuspended:
		{
			result = "Omx.Error.ComponentSuspended";
			return result;
		}
		case OMX_ErrorDynamicResourcesUnavailable:
		{
			result = "Omx.Error.DynamicResourcesUnavailable";
			return result;
		}
		case OMX_ErrorMbErrorsInFrame:
		{
			result = "Omx.Error.MbErrorsInFrame";
			return result;
		}
		case OMX_ErrorFormatNotDetected:
		{
			result = "Omx.Error.FormatNotDetected";
			return result;
		}
		case OMX_ErrorContentPipeOpenFailed:
		{
			result = "Omx.Error.ContentPipeOpenFailed";
			return result;
		}
		case OMX_ErrorContentPipeCreationFailed:
		{
			result = "Omx.Error.ContentPipeCreationFailed";
			return result;
		}
		case OMX_ErrorSeperateTablesUsed:
		{
			result = "Omx.Error.SeperateTablesUsed";
			return result;
		}
		case OMX_ErrorTunnelingUnsupported:
		{
			result = "Omx.Error.TunnelingUnsupported";
			return result;
		}
		default:
		{
			result = "(unknown)";
			return result;
		}
	}
}


static gpointer _g_error_copy0 (gpointer self) {
	return self ? g_error_copy (self) : NULL;
}


static void omx_try_run (OMX_ERRORTYPE err, const char* file, const char* function, gint line, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (file != NULL);
	g_return_if_fail (function != NULL);
	_inner_error_ = NULL;
	if (err != OMX_ErrorNone) {
		GError* e;
		e = g_error_new (omx_error_domain (), (gint) err, "%s (0x%x) in function %s at %s:%d", omx_error_to_string (err), err, function, file, line, NULL);
		_inner_error_ = _g_error_copy0 ((GError*) e);
		{
			g_propagate_error (error, _inner_error_);
			_g_error_free0 (e);
			return;
		}
		_g_error_free0 (e);
	}
}


static gboolean omx_buffer_header_eos (OMX_BUFFERHEADERTYPE* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = (self->nFlags & OMX_BUFFERFLAG_EOS) != 0;
	return result;
}


void mp3_player_play (Mp3Player* self, const char* filename, GError** error) {
	GError * _inner_error_;
	FILE* fd;
	OmxComponent* audiodec;
	gboolean eos_found;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	_inner_error_ = NULL;
	fd = fopen (filename, "rb");
	if (fd == NULL) {
		_inner_error_ = g_error_new (G_FILE_ERROR, G_FILE_ERROR_FAILED, "Error opening %s", filename);
		{
			g_propagate_error (error, _inner_error_);
			_fclose0 (fd);
			return;
		}
	}
	audiodec = omx_component_new (MP3_PLAYER_AUDIODEC_COMPONENT_NAME, OMX_IndexParamAudioInit);
	omx_try_run (OMX_Init (), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_set_name (audiodec, "audiodec");
	omx_component_init (audiodec, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_set_state (audiodec, OMX_StateIdle, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_allocate_ports (audiodec, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_wait_for_state_set (audiodec);
	omx_component_set_state (audiodec, OMX_StateExecuting, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_fill_output_buffers (audiodec, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_empty_input_buffers (audiodec, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_wait_for_state_set (audiodec);
	eos_found = FALSE;
	while (TRUE) {
		OmxPort* port;
		OMX_BUFFERHEADERTYPE* buffer;
		if (!(!eos_found)) {
			break;
		}
		port = omx_component_pop_port (audiodec);
		buffer = omx_port_pop_buffer (port);
		switch (port->definition.eDir) {
			case OMX_DirInput:
			{
				buffer->nOffset = (gsize) 0;
				buffer->nFilledLen = fread (buffer->pBuffer, 1, buffer->nAllocLen, fd);
				if (feof (fd)) {
					buffer->nFlags = buffer->nFlags | ((guint32) OMX_BUFFERFLAG_EOS);
				}
				break;
			}
			case OMX_DirOutput:
			{
				g_print ("Got %d bytes\n", (gint) buffer->nFilledLen);
				if (omx_buffer_header_eos (buffer)) {
					g_print ("Got eos\n");
					eos_found = TRUE;
				}
				break;
			}
			default:
			{
				break;
			}
		}
		omx_port_push_buffer (port, buffer, &_inner_error_);
		if (_inner_error_ != NULL) {
			g_propagate_error (error, _inner_error_);
			_g_object_unref0 (port);
			_fclose0 (fd);
			_g_object_unref0 (audiodec);
			return;
		}
		_g_object_unref0 (port);
	}
	omx_component_set_state (audiodec, OMX_StateIdle, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_wait_for_state_set (audiodec);
	omx_component_set_state (audiodec, OMX_StateLoaded, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_free_ports (audiodec, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_component_wait_for_state_set (audiodec);
	omx_component_free (audiodec, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	omx_try_run (OMX_Deinit (), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		_fclose0 (fd);
		_g_object_unref0 (audiodec);
		return;
	}
	_fclose0 (fd);
	_g_object_unref0 (audiodec);
}


Mp3Player* mp3_player_construct (GType object_type) {
	Mp3Player * self;
	self = (Mp3Player*) g_object_new (object_type, NULL);
	return self;
}


Mp3Player* mp3_player_new (void) {
	return mp3_player_construct (TYPE_MP3_PLAYER);
}


static void mp3_player_class_init (Mp3PlayerClass * klass) {
	mp3_player_parent_class = g_type_class_peek_parent (klass);
}


static void mp3_player_instance_init (Mp3Player * self) {
}


GType mp3_player_get_type (void) {
	static GType mp3_player_type_id = 0;
	if (mp3_player_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (Mp3PlayerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) mp3_player_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Mp3Player), 0, (GInstanceInitFunc) mp3_player_instance_init, NULL };
		mp3_player_type_id = g_type_register_static (G_TYPE_OBJECT, "Mp3Player", &g_define_type_info, 0);
	}
	return mp3_player_type_id;
}




