/* omx-glib.c generated by valac, the Vala compiler
 * generated from omx-glib.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <OMX_Core.h>
#include <OMX_Component.h>
#include <stdlib.h>
#include <string.h>
#include <bellagio/tsemaphore.h>
#include <omx-util.h>


#define OMX_TYPE_COMPONENT (omx_component_get_type ())
#define OMX_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMX_TYPE_COMPONENT, OmxComponent))
#define OMX_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMX_TYPE_COMPONENT, OmxComponentClass))
#define OMX_IS_COMPONENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMX_TYPE_COMPONENT))
#define OMX_IS_COMPONENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMX_TYPE_COMPONENT))
#define OMX_COMPONENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMX_TYPE_COMPONENT, OmxComponentClass))

typedef struct _OmxComponent OmxComponent;
typedef struct _OmxComponentClass OmxComponentClass;
typedef struct _OmxComponentPrivate OmxComponentPrivate;

#define OMX_TYPE_PORT (omx_port_get_type ())
#define OMX_PORT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), OMX_TYPE_PORT, OmxPort))
#define OMX_PORT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), OMX_TYPE_PORT, OmxPortClass))
#define OMX_IS_PORT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), OMX_TYPE_PORT))
#define OMX_IS_PORT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), OMX_TYPE_PORT))
#define OMX_PORT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), OMX_TYPE_PORT, OmxPortClass))

typedef struct _OmxPort OmxPort;
typedef struct _OmxPortClass OmxPortClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_async_queue_unref0(var) ((var == NULL) ? NULL : (var = (g_async_queue_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _OmxPortPrivate OmxPortPrivate;

struct _OmxComponent {
	GObject parent_instance;
	OmxComponentPrivate * priv;
	OMX_PORT_PARAM_TYPE port_param;
	OMX_HANDLETYPE handle;
	OmxPort** ports;
	gint ports_length1;
};

struct _OmxComponentClass {
	GObjectClass parent_class;
};

struct _OmxComponentPrivate {
	char* _component_name;
	OMX_INDEXTYPE _param_init_index;
	GAsyncQueue* buffer_queue;
	char* _name;
	tsem_t wait_for_state_sem;
};

struct _OmxPort {
	GObject parent_instance;
	OmxPortPrivate * priv;
	OMX_PARAM_PORTDEFINITIONTYPE definition;
	OMX_BUFFERHEADERTYPE** buffers;
	gint buffers_length1;
	GAsyncQueue* buffer_queue;
	OmxComponent* component;
};

struct _OmxPortClass {
	GObjectClass parent_class;
};

struct _OmxPortPrivate {
	char* _name;
};


static gpointer omx_component_parent_class = NULL;
static gpointer omx_port_parent_class = NULL;

GType omx_component_get_type (void);
GType omx_port_get_type (void);
#define OMX_COMPONENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), OMX_TYPE_COMPONENT, OmxComponentPrivate))
enum  {
	OMX_COMPONENT_DUMMY_PROPERTY,
	OMX_COMPONENT_NAME
};
static OMX_ERRORTYPE omx_component_event_handler (OmxComponent* self, OMX_HANDLETYPE component, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data);
static OMX_ERRORTYPE _omx_component_event_handler_omx_event_handler_func (OMX_HANDLETYPE component, gpointer self, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data);
static OMX_ERRORTYPE omx_component_buffer_done (OmxComponent* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer);
static OMX_ERRORTYPE _omx_component_buffer_done_omx_empty_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer);
static OMX_ERRORTYPE _omx_component_buffer_done_omx_fill_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer);
OmxComponent* omx_component_new (const char* component_name, OMX_INDEXTYPE param_init_index);
OmxComponent* omx_component_construct (GType object_type, const char* component_name, OMX_INDEXTYPE param_init_index);
void omx_component_init (OmxComponent* self, GError** error);
void omx_component_free (OmxComponent* self, GError** error);
OmxPort* omx_port_new (OmxComponent* parent_component, guint32 port_index);
OmxPort* omx_port_construct (GType object_type, OmxComponent* parent_component, guint32 port_index);
void omx_port_init (OmxPort* self, GError** error);
void omx_port_allocate_buffers (OmxPort* self, GError** error);
const char* omx_component_get_name (OmxComponent* self);
void omx_port_set_name (OmxPort* self, const char* value);
void omx_component_allocate_ports (OmxComponent* self, GError** error);
void omx_port_free_buffers (OmxPort* self, GError** error);
void omx_component_free_ports (OmxComponent* self, GError** error);
void omx_port_push_buffer (OmxPort* self, OMX_BUFFERHEADERTYPE* buffer, GError** error);
OMX_BUFFERHEADERTYPE* omx_port_pop_buffer (OmxPort* self);
void omx_component_fill_output_buffers (OmxComponent* self, GError** error);
void omx_component_empty_input_buffers (OmxComponent* self, GError** error);
OmxPort* omx_component_pop_port (OmxComponent* self);
void omx_component_wait_for_state_set (OmxComponent* self);
void omx_component_set_state (OmxComponent* self, OMX_STATETYPE state, GError** error);
OMX_STATETYPE omx_component_get_state (OmxComponent* self, GError** error);
void omx_component_set_name (OmxComponent* self, const char* value);
static void omx_component_finalize (GObject* obj);
static void omx_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void omx_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
#define OMX_PORT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), OMX_TYPE_PORT, OmxPortPrivate))
enum  {
	OMX_PORT_DUMMY_PROPERTY,
	OMX_PORT_NAME
};
const char* omx_port_get_name (OmxPort* self);
static void omx_port_finalize (GObject* obj);
static void omx_port_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void omx_port_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);

static const OMX_CALLBACKTYPE OMX_COMPONENT_callbacks = {_omx_component_event_handler_omx_event_handler_func, _omx_component_buffer_done_omx_empty_buffer_done_func, _omx_component_buffer_done_omx_fill_buffer_done_func};


static OMX_ERRORTYPE _omx_component_event_handler_omx_event_handler_func (OMX_HANDLETYPE component, gpointer self, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data) {
	return omx_component_event_handler (self, component, event, data1, data2, event_data);
}


static OMX_ERRORTYPE _omx_component_buffer_done_omx_empty_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer) {
	return omx_component_buffer_done (self, component, buffer);
}


static OMX_ERRORTYPE _omx_component_buffer_done_omx_fill_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer) {
	return omx_component_buffer_done (self, component, buffer);
}


OmxComponent* omx_component_construct (GType object_type, const char* component_name, OMX_INDEXTYPE param_init_index) {
	OmxComponent * self;
	char* _tmp0_;
	GAsyncQueue* _tmp1_;
	g_return_val_if_fail (component_name != NULL, NULL);
	self = (OmxComponent*) g_object_new (object_type, NULL);
	self->priv->_component_name = (_tmp0_ = g_strdup (component_name), _g_free0 (self->priv->_component_name), _tmp0_);
	self->priv->_param_init_index = param_init_index;
	self->priv->buffer_queue = (_tmp1_ = g_async_queue_new (), _g_async_queue_unref0 (self->priv->buffer_queue), _tmp1_);
	return self;
}


OmxComponent* omx_component_new (const char* component_name, OMX_INDEXTYPE param_init_index) {
	return omx_component_construct (OMX_TYPE_COMPONENT, component_name, param_init_index);
}


static GQuark omx_error_domain (void) {
	GQuark result;
	result = g_quark_from_string ("Omx.Error");
	return result;
}


static const char* omx_error_to_string (OMX_ERRORTYPE self) {
	const char* result;
	switch (self) {
		case OMX_ErrorNone:
		{
			result = "Omx.Error.None";
			return result;
		}
		case OMX_ErrorInsufficientResources:
		{
			result = "Omx.Error.InsufficientResources";
			return result;
		}
		case OMX_ErrorUndefined:
		{
			result = "Omx.Error.Undefined";
			return result;
		}
		case OMX_ErrorInvalidComponentName:
		{
			result = "Omx.Error.InvalidComponentName";
			return result;
		}
		case OMX_ErrorComponentNotFound:
		{
			result = "Omx.Error.ComponentNotFound";
			return result;
		}
		case OMX_ErrorInvalidComponent:
		{
			result = "Omx.Error.InvalidComponent";
			return result;
		}
		case OMX_ErrorBadParameter:
		{
			result = "Omx.Error.BadParameter";
			return result;
		}
		case OMX_ErrorNotImplemented:
		{
			result = "Omx.Error.NotImplemented";
			return result;
		}
		case OMX_ErrorUnderflow:
		{
			result = "Omx.Error.Underflow";
			return result;
		}
		case OMX_ErrorOverflow:
		{
			result = "Omx.Error.Overflow";
			return result;
		}
		case OMX_ErrorHardware:
		{
			result = "Omx.Error.Hardware";
			return result;
		}
		case OMX_ErrorInvalidState:
		{
			result = "Omx.Error.InvalidState";
			return result;
		}
		case OMX_ErrorStreamCorrupt:
		{
			result = "Omx.Error.StreamCorrupt";
			return result;
		}
		case OMX_ErrorPortsNotCompatible:
		{
			result = "Omx.Error.PortsNotCompatible";
			return result;
		}
		case OMX_ErrorResourcesLost:
		{
			result = "Omx.Error.ResourcesLost";
			return result;
		}
		case OMX_ErrorNoMore:
		{
			result = "Omx.Error.NoMore";
			return result;
		}
		case OMX_ErrorVersionMismatch:
		{
			result = "Omx.Error.VersionMismatch";
			return result;
		}
		case OMX_ErrorNotReady:
		{
			result = "Omx.Error.NotReady";
			return result;
		}
		case OMX_ErrorTimeout:
		{
			result = "Omx.Error.Timeout";
			return result;
		}
		case OMX_ErrorSameState:
		{
			result = "Omx.Error.SameState";
			return result;
		}
		case OMX_ErrorResourcesPreempted:
		{
			result = "Omx.Error.ResourcesPreempted";
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringAllocation:
		{
			result = "Omx.Error.PortUnresponsiveDuringAllocation";
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringDeallocation:
		{
			result = "Omx.Error.PortUnresponsiveDuringDeallocation";
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringStop:
		{
			result = "Omx.Error.PortUnresponsiveDuringStop";
			return result;
		}
		case OMX_ErrorIncorrectStateTransition:
		{
			result = "Omx.Error.IncorrectStateTransition";
			return result;
		}
		case OMX_ErrorIncorrectStateOperation:
		{
			result = "Omx.Error.IncorrectStateOperation";
			return result;
		}
		case OMX_ErrorUnsupportedSetting:
		{
			result = "Omx.Error.UnsupportedSetting";
			return result;
		}
		case OMX_ErrorUnsupportedIndex:
		{
			result = "Omx.Error.UnsupportedIndex";
			return result;
		}
		case OMX_ErrorBadPortIndex:
		{
			result = "Omx.Error.BadPortIndex";
			return result;
		}
		case OMX_ErrorPortUnpopulated:
		{
			result = "Omx.Error.PortUnpopulated";
			return result;
		}
		case OMX_ErrorComponentSuspended:
		{
			result = "Omx.Error.ComponentSuspended";
			return result;
		}
		case OMX_ErrorDynamicResourcesUnavailable:
		{
			result = "Omx.Error.DynamicResourcesUnavailable";
			return result;
		}
		case OMX_ErrorMbErrorsInFrame:
		{
			result = "Omx.Error.MbErrorsInFrame";
			return result;
		}
		case OMX_ErrorFormatNotDetected:
		{
			result = "Omx.Error.FormatNotDetected";
			return result;
		}
		case OMX_ErrorContentPipeOpenFailed:
		{
			result = "Omx.Error.ContentPipeOpenFailed";
			return result;
		}
		case OMX_ErrorContentPipeCreationFailed:
		{
			result = "Omx.Error.ContentPipeCreationFailed";
			return result;
		}
		case OMX_ErrorSeperateTablesUsed:
		{
			result = "Omx.Error.SeperateTablesUsed";
			return result;
		}
		case OMX_ErrorTunnelingUnsupported:
		{
			result = "Omx.Error.TunnelingUnsupported";
			return result;
		}
		default:
		{
			result = "(unknown)";
			return result;
		}
	}
}


static gpointer _g_error_copy0 (gpointer self) {
	return self ? g_error_copy (self) : NULL;
}


static void omx_try_run (OMX_ERRORTYPE err, const char* file, const char* function, gint line, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (file != NULL);
	g_return_if_fail (function != NULL);
	_inner_error_ = NULL;
	if (err != OMX_ErrorNone) {
		GError* e;
		e = g_error_new (omx_error_domain (), (gint) err, "%s (0x%x) in function %s at %s:%d", omx_error_to_string (err), err, function, file, line, NULL);
		_inner_error_ = _g_error_copy0 ((GError*) e);
		{
			g_propagate_error (error, _inner_error_);
			_g_error_free0 (e);
			return;
		}
		_g_error_free0 (e);
	}
}


void omx_component_init (OmxComponent* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_GetHandle (&self->handle, self->priv->_component_name, self, &OMX_COMPONENT_callbacks), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_structure_init (&self->port_param);
	omx_try_run (OMX_GetParameter (self->handle, (guint) self->priv->_param_init_index, &self->port_param), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


void omx_component_free (OmxComponent* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_FreeHandle (self->handle), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->handle = NULL;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void omx_component_allocate_ports (OmxComponent* self, GError** error) {
	GError * _inner_error_;
	guint n_ports;
	OmxPort** _tmp0_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	n_ports = (guint) (self->port_param.nPorts - self->port_param.nStartPortNumber);
	self->ports = (_tmp0_ = g_new0 (OmxPort*, n_ports + 1), self->ports = (_vala_array_free (self->ports, self->ports_length1, (GDestroyNotify) g_object_unref), NULL), self->ports_length1 = n_ports, _tmp0_);
	{
		guint i;
		i = (guint) 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				OmxPort* port;
				char* _tmp2_;
				OmxPort* _tmp3_;
				if (!_tmp1_) {
					i++;
				}
				_tmp1_ = FALSE;
				if (!(i < n_ports)) {
					break;
				}
				port = omx_port_new (self, (guint32) i);
				omx_port_init (port, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					_g_object_unref0 (port);
					return;
				}
				omx_port_allocate_buffers (port, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					_g_object_unref0 (port);
					return;
				}
				omx_port_set_name (port, _tmp2_ = g_strdup_printf ("%s:port%u", self->priv->_name, i));
				_g_free0 (_tmp2_);
				self->ports[i] = (_tmp3_ = _g_object_ref0 (port), _g_object_unref0 (self->ports[i]), _tmp3_);
				_g_object_unref0 (port);
			}
		}
	}
}


void omx_component_free_ports (OmxComponent* self, GError** error) {
	GError * _inner_error_;
	OmxPort** _tmp0_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	{
		OmxPort** port_collection;
		int port_collection_length1;
		int port_it;
		port_collection = self->ports;
		port_collection_length1 = self->ports_length1;
		for (port_it = 0; port_it < self->ports_length1; port_it = port_it + 1) {
			OmxPort* port;
			port = _g_object_ref0 (port_collection[port_it]);
			{
				omx_port_free_buffers (port, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					_g_object_unref0 (port);
					return;
				}
				_g_object_unref0 (port);
			}
		}
	}
	self->ports = (_tmp0_ = NULL, self->ports = (_vala_array_free (self->ports, self->ports_length1, (GDestroyNotify) g_object_unref), NULL), self->ports_length1 = 0, _tmp0_);
}


void omx_component_fill_output_buffers (OmxComponent* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	{
		OmxPort** port_collection;
		int port_collection_length1;
		int port_it;
		port_collection = self->ports;
		port_collection_length1 = self->ports_length1;
		for (port_it = 0; port_it < self->ports_length1; port_it = port_it + 1) {
			OmxPort* port;
			port = _g_object_ref0 (port_collection[port_it]);
			{
				if (port->definition.eDir == OMX_DirOutput) {
					{
						gint i;
						i = 0;
						{
							gboolean _tmp0_;
							_tmp0_ = TRUE;
							while (TRUE) {
								if (!_tmp0_) {
									i++;
								}
								_tmp0_ = FALSE;
								if (!(i < port->buffers_length1)) {
									break;
								}
								omx_port_push_buffer (port, omx_port_pop_buffer (port), &_inner_error_);
								if (_inner_error_ != NULL) {
									g_propagate_error (error, _inner_error_);
									_g_object_unref0 (port);
									return;
								}
							}
						}
					}
				}
				_g_object_unref0 (port);
			}
		}
	}
}


void omx_component_empty_input_buffers (OmxComponent* self, GError** error) {
	g_return_if_fail (self != NULL);
	{
		OmxPort** port_collection;
		int port_collection_length1;
		int port_it;
		port_collection = self->ports;
		port_collection_length1 = self->ports_length1;
		for (port_it = 0; port_it < self->ports_length1; port_it = port_it + 1) {
			OmxPort* port;
			port = _g_object_ref0 (port_collection[port_it]);
			{
				if (port->definition.eDir == OMX_DirInput) {
					{
						OMX_BUFFERHEADERTYPE** buffer_collection;
						int buffer_collection_length1;
						int buffer_it;
						buffer_collection = port->buffers;
						buffer_collection_length1 = port->buffers_length1;
						for (buffer_it = 0; buffer_it < port->buffers_length1; buffer_it = buffer_it + 1) {
							OMX_BUFFERHEADERTYPE* buffer;
							buffer = buffer_collection[buffer_it];
							{
								g_async_queue_push (self->priv->buffer_queue, buffer);
							}
						}
					}
				}
				_g_object_unref0 (port);
			}
		}
	}
}


OmxPort* omx_component_pop_port (OmxComponent* self) {
	OmxPort* result;
	OMX_BUFFERHEADERTYPE* buffer;
	void* _tmp0_;
	OmxPort* port;
	g_return_val_if_fail (self != NULL, NULL);
	buffer = (OMX_BUFFERHEADERTYPE*) g_async_queue_pop (self->priv->buffer_queue);
	port = _g_object_ref0 ((_tmp0_ = buffer->pAppPrivate, OMX_IS_PORT (_tmp0_) ? ((OmxPort*) _tmp0_) : NULL));
	result = port;
	return result;
}


void omx_component_wait_for_state_set (OmxComponent* self) {
	g_return_if_fail (self != NULL);
	tsem_down (&self->priv->wait_for_state_sem);
}


void omx_component_set_state (OmxComponent* self, OMX_STATETYPE state, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_SendCommand (self->handle, OMX_CommandStateSet, (guint) state, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


OMX_STATETYPE omx_component_get_state (OmxComponent* self, GError** error) {
	OMX_STATETYPE result;
	GError * _inner_error_;
	OMX_STATETYPE state = 0;
	g_return_val_if_fail (self != NULL, 0);
	_inner_error_ = NULL;
	omx_try_run (OMX_GetState (self->handle, &state), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return 0;
	}
	result = state;
	return result;
}


static OMX_ERRORTYPE omx_component_event_handler (OmxComponent* self, OMX_HANDLETYPE component, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data) {
	OMX_ERRORTYPE result;
	g_return_val_if_fail (self != NULL, 0);
	switch (event) {
		case OMX_EventCmdComplete:
		{
			switch (data1) {
				case OMX_CommandStateSet:
				{
					tsem_up (&self->priv->wait_for_state_sem);
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	result = OMX_ErrorNone;
	return result;
}


static OMX_ERRORTYPE omx_component_buffer_done (OmxComponent* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer) {
	OMX_ERRORTYPE result;
	void* _tmp0_;
	OmxPort* port;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (buffer != NULL, 0);
	port = _g_object_ref0 ((_tmp0_ = buffer->pAppPrivate, OMX_IS_PORT (_tmp0_) ? ((OmxPort*) _tmp0_) : NULL));
	g_async_queue_push (port->buffer_queue, buffer);
	g_async_queue_push (self->priv->buffer_queue, buffer);
	result = OMX_ErrorNone;
	_g_object_unref0 (port);
	return result;
}


const char* omx_component_get_name (OmxComponent* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_name;
	return result;
}


void omx_component_set_name (OmxComponent* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_name), _tmp0_);
	g_object_notify ((GObject *) self, "name");
}


static void omx_component_class_init (OmxComponentClass * klass) {
	omx_component_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (OmxComponentPrivate));
	G_OBJECT_CLASS (klass)->get_property = omx_component_get_property;
	G_OBJECT_CLASS (klass)->set_property = omx_component_set_property;
	G_OBJECT_CLASS (klass)->finalize = omx_component_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OMX_COMPONENT_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void omx_component_instance_init (OmxComponent * self) {
	self->priv = OMX_COMPONENT_GET_PRIVATE (self);
}


static void omx_component_finalize (GObject* obj) {
	OmxComponent * self;
	self = OMX_COMPONENT (obj);
	_g_free0 (self->priv->_component_name);
	_g_async_queue_unref0 (self->priv->buffer_queue);
	self->ports = (_vala_array_free (self->ports, self->ports_length1, (GDestroyNotify) g_object_unref), NULL);
	_g_free0 (self->priv->_name);
	G_OBJECT_CLASS (omx_component_parent_class)->finalize (obj);
}


GType omx_component_get_type (void) {
	static GType omx_component_type_id = 0;
	if (omx_component_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (OmxComponentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) omx_component_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OmxComponent), 0, (GInstanceInitFunc) omx_component_instance_init, NULL };
		omx_component_type_id = g_type_register_static (G_TYPE_OBJECT, "OmxComponent", &g_define_type_info, 0);
	}
	return omx_component_type_id;
}


static void omx_component_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	OmxComponent * self;
	self = OMX_COMPONENT (object);
	switch (property_id) {
		case OMX_COMPONENT_NAME:
		g_value_set_string (value, omx_component_get_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void omx_component_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	OmxComponent * self;
	self = OMX_COMPONENT (object);
	switch (property_id) {
		case OMX_COMPONENT_NAME:
		omx_component_set_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


OmxPort* omx_port_construct (GType object_type, OmxComponent* parent_component, guint32 port_index) {
	OmxPort * self;
	OmxComponent* _tmp0_;
	GAsyncQueue* _tmp1_;
	g_return_val_if_fail (parent_component != NULL, NULL);
	self = (OmxPort*) g_object_new (object_type, NULL);
	self->component = (_tmp0_ = _g_object_ref0 (parent_component), _g_object_unref0 (self->component), _tmp0_);
	self->buffer_queue = (_tmp1_ = g_async_queue_new (), _g_async_queue_unref0 (self->buffer_queue), _tmp1_);
	omx_structure_init (&self->definition);
	self->definition.nPortIndex = port_index;
	return self;
}


OmxPort* omx_port_new (OmxComponent* parent_component, guint32 port_index) {
	return omx_port_construct (OMX_TYPE_PORT, parent_component, port_index);
}


void omx_port_init (OmxPort* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_GetParameter (self->component->handle, (guint) OMX_IndexParamPortDefinition, &self->definition), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


void omx_port_allocate_buffers (OmxPort* self, GError** error) {
	GError * _inner_error_;
	OMX_BUFFERHEADERTYPE** _tmp0_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	self->buffers = (_tmp0_ = g_new0 (OMX_BUFFERHEADERTYPE*, self->definition.nBufferCountActual + 1), self->buffers = (g_free (self->buffers), NULL), self->buffers_length1 = self->definition.nBufferCountActual, _tmp0_);
	{
		guint i;
		i = (guint) 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				if (!_tmp1_) {
					i++;
				}
				_tmp1_ = FALSE;
				if (!(i < self->definition.nBufferCountActual)) {
					break;
				}
				omx_try_run (OMX_AllocateBuffer (self->component->handle, &self->buffers[i], (guint) self->definition.nPortIndex, self, (guint) self->definition.nBufferSize), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
				g_async_queue_push (self->buffer_queue, self->buffers[i]);
			}
		}
	}
}


void omx_port_free_buffers (OmxPort* self, GError** error) {
	GError * _inner_error_;
	OMX_BUFFERHEADERTYPE** _tmp0_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	{
		OMX_BUFFERHEADERTYPE** buffer_collection;
		int buffer_collection_length1;
		int buffer_it;
		buffer_collection = self->buffers;
		buffer_collection_length1 = self->buffers_length1;
		for (buffer_it = 0; buffer_it < self->buffers_length1; buffer_it = buffer_it + 1) {
			OMX_BUFFERHEADERTYPE* buffer;
			buffer = buffer_collection[buffer_it];
			{
				omx_try_run (OMX_FreeBuffer (self->component->handle, (guint) self->definition.nPortIndex, buffer), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
			}
		}
	}
	self->buffers = (_tmp0_ = NULL, self->buffers = (g_free (self->buffers), NULL), self->buffers_length1 = 0, _tmp0_);
}


OMX_BUFFERHEADERTYPE* omx_port_pop_buffer (OmxPort* self) {
	OMX_BUFFERHEADERTYPE* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = (OMX_BUFFERHEADERTYPE*) g_async_queue_pop (self->buffer_queue);
	return result;
}


void omx_port_push_buffer (OmxPort* self, OMX_BUFFERHEADERTYPE* buffer, GError** error) {
	void* _tmp0_;
	OmxPort* port;
	OMX_HANDLETYPE handle;
	g_return_if_fail (self != NULL);
	g_return_if_fail (buffer != NULL);
	port = _g_object_ref0 ((_tmp0_ = buffer->pAppPrivate, OMX_IS_PORT (_tmp0_) ? ((OmxPort*) _tmp0_) : NULL));
	handle = port->component->handle;
	switch (port->definition.eDir) {
		case OMX_DirInput:
		{
			OMX_EmptyThisBuffer (handle, buffer);
			break;
		}
		case OMX_DirOutput:
		{
			OMX_FillThisBuffer (handle, buffer);
			break;
		}
		default:
		{
			break;
		}
	}
	_g_object_unref0 (port);
}


const char* omx_port_get_name (OmxPort* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_name;
	return result;
}


void omx_port_set_name (OmxPort* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_name), _tmp0_);
	g_object_notify ((GObject *) self, "name");
}


static void omx_port_class_init (OmxPortClass * klass) {
	omx_port_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (OmxPortPrivate));
	G_OBJECT_CLASS (klass)->get_property = omx_port_get_property;
	G_OBJECT_CLASS (klass)->set_property = omx_port_set_property;
	G_OBJECT_CLASS (klass)->finalize = omx_port_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), OMX_PORT_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void omx_port_instance_init (OmxPort * self) {
	self->priv = OMX_PORT_GET_PRIVATE (self);
}


static void omx_port_finalize (GObject* obj) {
	OmxPort * self;
	self = OMX_PORT (obj);
	self->buffers = (g_free (self->buffers), NULL);
	_g_async_queue_unref0 (self->buffer_queue);
	_g_object_unref0 (self->component);
	_g_free0 (self->priv->_name);
	G_OBJECT_CLASS (omx_port_parent_class)->finalize (obj);
}


GType omx_port_get_type (void) {
	static GType omx_port_type_id = 0;
	if (omx_port_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (OmxPortClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) omx_port_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (OmxPort), 0, (GInstanceInitFunc) omx_port_instance_init, NULL };
		omx_port_type_id = g_type_register_static (G_TYPE_OBJECT, "OmxPort", &g_define_type_info, 0);
	}
	return omx_port_type_id;
}


static void omx_port_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	OmxPort * self;
	self = OMX_PORT (object);
	switch (property_id) {
		case OMX_PORT_NAME:
		g_value_set_string (value, omx_port_get_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void omx_port_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	OmxPort * self;
	self = OMX_PORT (object);
	switch (property_id) {
		case OMX_PORT_NAME:
		omx_port_set_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}




