/* simple-mp3-player.c generated by valac, the Vala compiler
 * generated from simple-mp3-player.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <bellagio/tsemaphore.h>
#include <OMX_Component.h>
#include <OMX_Core.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_SIMPLE_MP3_PLAYER (simple_mp3_player_get_type ())
#define SIMPLE_MP3_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SIMPLE_MP3_PLAYER, SimpleMp3Player))
#define SIMPLE_MP3_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SIMPLE_MP3_PLAYER, SimpleMp3PlayerClass))
#define IS_SIMPLE_MP3_PLAYER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SIMPLE_MP3_PLAYER))
#define IS_SIMPLE_MP3_PLAYER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SIMPLE_MP3_PLAYER))
#define SIMPLE_MP3_PLAYER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SIMPLE_MP3_PLAYER, SimpleMp3PlayerClass))

typedef struct _SimpleMp3Player SimpleMp3Player;
typedef struct _SimpleMp3PlayerClass SimpleMp3PlayerClass;
typedef struct _SimpleMp3PlayerPrivate SimpleMp3PlayerPrivate;
#define _fclose0(var) ((var == NULL) ? NULL : (var = (fclose (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _SimpleMp3Player {
	GObject parent_instance;
	SimpleMp3PlayerPrivate * priv;
};

struct _SimpleMp3PlayerClass {
	GObjectClass parent_class;
};

struct _SimpleMp3PlayerPrivate {
	tsem_t audiodec_sem;
	tsem_t audiosink_sem;
	tsem_t eos_sem;
	OMX_HANDLETYPE audiodec_handle;
	OMX_HANDLETYPE audiosink_handle;
	OMX_BUFFERHEADERTYPE** in_buffer_audiosink;
	gint in_buffer_audiosink_length1;
	gint in_buffer_audiosink_size;
	OMX_BUFFERHEADERTYPE** in_buffer_audiodec;
	gint in_buffer_audiodec_length1;
	gint in_buffer_audiodec_size;
	OMX_BUFFERHEADERTYPE** out_buffer_audiodec;
	gint out_buffer_audiodec_length1;
	gint out_buffer_audiodec_size;
	FILE* fd;
	gboolean eos_found;
};


static gpointer simple_mp3_player_parent_class = NULL;

GType simple_mp3_player_get_type (void);
#define SIMPLE_MP3_PLAYER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SIMPLE_MP3_PLAYER, SimpleMp3PlayerPrivate))
enum  {
	SIMPLE_MP3_PLAYER_DUMMY_PROPERTY
};
#define SIMPLE_MP3_PLAYER_n_buffers 2
#define SIMPLE_MP3_PLAYER_buffer_out_size (4 * 8192)
#define SIMPLE_MP3_PLAYER_buffer_in_size 4096
static OMX_ERRORTYPE simple_mp3_player_audiodec_event_handler (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data);
static OMX_ERRORTYPE _simple_mp3_player_audiodec_event_handler_omx_event_handler_func (OMX_HANDLETYPE component, gpointer self, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data);
static OMX_ERRORTYPE simple_mp3_player_audiodec_empty_buffer_done (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer);
static OMX_ERRORTYPE _simple_mp3_player_audiodec_empty_buffer_done_omx_empty_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer);
static OMX_ERRORTYPE simple_mp3_player_audiodec_fill_buffer_done (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer);
static OMX_ERRORTYPE _simple_mp3_player_audiodec_fill_buffer_done_omx_fill_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer);
static OMX_ERRORTYPE simple_mp3_player_audiosink_event_handler (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data);
static OMX_ERRORTYPE _simple_mp3_player_audiosink_event_handler_omx_event_handler_func (OMX_HANDLETYPE component, gpointer self, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data);
static OMX_ERRORTYPE simple_mp3_player_audiosink_empty_buffer_done (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer);
static OMX_ERRORTYPE _simple_mp3_player_audiosink_empty_buffer_done_omx_empty_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer);
static void simple_mp3_player_get_handles (SimpleMp3Player* self, GError** error);
static void simple_mp3_player_pass_to_idle_and_allocate_buffers (SimpleMp3Player* self, GError** error);
static void simple_mp3_player_pass_to_executing (SimpleMp3Player* self, GError** error);
static void simple_mp3_player_move_buffers (SimpleMp3Player* self, const char* filename, GError** error);
static void simple_mp3_player_pass_to_idle (SimpleMp3Player* self, GError** error);
static void simple_mp3_player_pass_to_loaded_and_free_buffers (SimpleMp3Player* self, GError** error);
static void simple_mp3_player_free_handles (SimpleMp3Player* self, GError** error);
void simple_mp3_player_decode (SimpleMp3Player* self, const char* filename, GError** error);
SimpleMp3Player* simple_mp3_player_new (void);
SimpleMp3Player* simple_mp3_player_construct (GType object_type);
static GObject * simple_mp3_player_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void simple_mp3_player_finalize (GObject* obj);
gint _main (char** args, int args_length1);

static const OMX_CALLBACKTYPE SIMPLE_MP3_PLAYER_audiodec_callbacks = {_simple_mp3_player_audiodec_event_handler_omx_event_handler_func, _simple_mp3_player_audiodec_empty_buffer_done_omx_empty_buffer_done_func, _simple_mp3_player_audiodec_fill_buffer_done_omx_fill_buffer_done_func};
static const OMX_CALLBACKTYPE SIMPLE_MP3_PLAYER_audiosink_callbacks = {_simple_mp3_player_audiosink_event_handler_omx_event_handler_func, _simple_mp3_player_audiosink_empty_buffer_done_omx_empty_buffer_done_func, NULL};


static OMX_ERRORTYPE _simple_mp3_player_audiodec_event_handler_omx_event_handler_func (OMX_HANDLETYPE component, gpointer self, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data) {
	return simple_mp3_player_audiodec_event_handler (self, component, event, data1, data2, event_data);
}


static OMX_ERRORTYPE _simple_mp3_player_audiodec_empty_buffer_done_omx_empty_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer) {
	return simple_mp3_player_audiodec_empty_buffer_done (self, component, buffer);
}


static OMX_ERRORTYPE _simple_mp3_player_audiodec_fill_buffer_done_omx_fill_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer) {
	return simple_mp3_player_audiodec_fill_buffer_done (self, component, buffer);
}


static OMX_ERRORTYPE _simple_mp3_player_audiosink_event_handler_omx_event_handler_func (OMX_HANDLETYPE component, gpointer self, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data) {
	return simple_mp3_player_audiosink_event_handler (self, component, event, data1, data2, event_data);
}


static OMX_ERRORTYPE _simple_mp3_player_audiosink_empty_buffer_done_omx_empty_buffer_done_func (OMX_HANDLETYPE component, gpointer self, OMX_BUFFERHEADERTYPE* buffer) {
	return simple_mp3_player_audiosink_empty_buffer_done (self, component, buffer);
}


static OMX_ERRORTYPE simple_mp3_player_audiodec_event_handler (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data) {
	OMX_ERRORTYPE result;
	g_return_val_if_fail (self != NULL, 0);
	switch (event) {
		case OMX_EventCmdComplete:
		{
			switch (data1) {
				case OMX_CommandStateSet:
				{
					tsem_up (&self->priv->audiodec_sem);
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		case OMX_EventBufferFlag:
		{
			switch (data2) {
				case OMX_BUFFERFLAG_EOS:
				{
					tsem_up (&self->priv->eos_sem);
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	result = OMX_ErrorNone;
	return result;
}


static OMX_ERRORTYPE simple_mp3_player_audiodec_empty_buffer_done (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer) {
	OMX_ERRORTYPE result;
	gsize data_read;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (buffer != NULL, 0);
	if (self->priv->eos_found) {
		result = OMX_ErrorNone;
		return result;
	}
	data_read = fread (buffer->pBuffer, 1, buffer->nAllocLen, self->priv->fd);
	buffer->nOffset = (gsize) 0;
	if (data_read == 0) {
		buffer->nFilledLen = (gsize) 0;
		buffer->nFlags = buffer->nFlags | ((guint32) OMX_BUFFERFLAG_EOS);
		self->priv->eos_found = TRUE;
	} else {
		buffer->nFilledLen = data_read;
	}
	result = OMX_EmptyThisBuffer (component, buffer);
	return result;
}


static OMX_ERRORTYPE simple_mp3_player_audiodec_fill_buffer_done (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer) {
	OMX_ERRORTYPE result;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (buffer != NULL, 0);
	if (buffer->nFilledLen == 0) {
		result = OMX_ErrorNone;
		return result;
	} else {
		result = OMX_EmptyThisBuffer (self->priv->audiosink_handle, buffer);
		return result;
	}
}


static OMX_ERRORTYPE simple_mp3_player_audiosink_event_handler (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_EVENTTYPE event, guint32 data1, guint32 data2, void* event_data) {
	OMX_ERRORTYPE result;
	g_return_val_if_fail (self != NULL, 0);
	switch (event) {
		case OMX_EventCmdComplete:
		{
			switch (data1) {
				case OMX_CommandStateSet:
				{
					tsem_up (&self->priv->audiosink_sem);
					break;
				}
				default:
				{
					break;
				}
			}
			break;
		}
		default:
		{
			break;
		}
	}
	result = OMX_ErrorNone;
	return result;
}


static OMX_ERRORTYPE simple_mp3_player_audiosink_empty_buffer_done (SimpleMp3Player* self, OMX_HANDLETYPE component, OMX_BUFFERHEADERTYPE* buffer) {
	OMX_ERRORTYPE result;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (buffer != NULL, 0);
	result = OMX_FillThisBuffer (self->priv->audiodec_handle, buffer);
	return result;
}


static GQuark omx_error_domain (void) {
	GQuark result;
	result = g_quark_from_string ("Omx.Error");
	return result;
}


static char* omx_error_to_string (OMX_ERRORTYPE self) {
	char* result;
	switch (self) {
		case OMX_ErrorNone:
		{
			result = g_strdup ("Omx.Error.None");
			return result;
		}
		case OMX_ErrorInsufficientResources:
		{
			result = g_strdup ("Omx.Error.InsufficientResources");
			return result;
		}
		case OMX_ErrorUndefined:
		{
			result = g_strdup ("Omx.Error.Undefined");
			return result;
		}
		case OMX_ErrorInvalidComponentName:
		{
			result = g_strdup ("Omx.Error.InvalidComponentName");
			return result;
		}
		case OMX_ErrorComponentNotFound:
		{
			result = g_strdup ("Omx.Error.ComponentNotFound");
			return result;
		}
		case OMX_ErrorInvalidComponent:
		{
			result = g_strdup ("Omx.Error.InvalidComponent");
			return result;
		}
		case OMX_ErrorBadParameter:
		{
			result = g_strdup ("Omx.Error.BadParameter");
			return result;
		}
		case OMX_ErrorNotImplemented:
		{
			result = g_strdup ("Omx.Error.NotImplemented");
			return result;
		}
		case OMX_ErrorUnderflow:
		{
			result = g_strdup ("Omx.Error.Underflow");
			return result;
		}
		case OMX_ErrorOverflow:
		{
			result = g_strdup ("Omx.Error.Overflow");
			return result;
		}
		case OMX_ErrorHardware:
		{
			result = g_strdup ("Omx.Error.Hardware");
			return result;
		}
		case OMX_ErrorInvalidState:
		{
			result = g_strdup ("Omx.Error.InvalidState");
			return result;
		}
		case OMX_ErrorStreamCorrupt:
		{
			result = g_strdup ("Omx.Error.StreamCorrupt");
			return result;
		}
		case OMX_ErrorPortsNotCompatible:
		{
			result = g_strdup ("Omx.Error.PortsNotCompatible");
			return result;
		}
		case OMX_ErrorResourcesLost:
		{
			result = g_strdup ("Omx.Error.ResourcesLost");
			return result;
		}
		case OMX_ErrorNoMore:
		{
			result = g_strdup ("Omx.Error.NoMore");
			return result;
		}
		case OMX_ErrorVersionMismatch:
		{
			result = g_strdup ("Omx.Error.VersionMismatch");
			return result;
		}
		case OMX_ErrorNotReady:
		{
			result = g_strdup ("Omx.Error.NotReady");
			return result;
		}
		case OMX_ErrorTimeout:
		{
			result = g_strdup ("Omx.Error.Timeout");
			return result;
		}
		case OMX_ErrorSameState:
		{
			result = g_strdup ("Omx.Error.SameState");
			return result;
		}
		case OMX_ErrorResourcesPreempted:
		{
			result = g_strdup ("Omx.Error.ResourcesPreempted");
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringAllocation:
		{
			result = g_strdup ("Omx.Error.PortUnresponsiveDuringAllocation");
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringDeallocation:
		{
			result = g_strdup ("Omx.Error.PortUnresponsiveDuringDeallocation");
			return result;
		}
		case OMX_ErrorPortUnresponsiveDuringStop:
		{
			result = g_strdup ("Omx.Error.PortUnresponsiveDuringStop");
			return result;
		}
		case OMX_ErrorIncorrectStateTransition:
		{
			result = g_strdup ("Omx.Error.IncorrectStateTransition");
			return result;
		}
		case OMX_ErrorIncorrectStateOperation:
		{
			result = g_strdup ("Omx.Error.IncorrectStateOperation");
			return result;
		}
		case OMX_ErrorUnsupportedSetting:
		{
			result = g_strdup ("Omx.Error.UnsupportedSetting");
			return result;
		}
		case OMX_ErrorUnsupportedIndex:
		{
			result = g_strdup ("Omx.Error.UnsupportedIndex");
			return result;
		}
		case OMX_ErrorBadPortIndex:
		{
			result = g_strdup ("Omx.Error.BadPortIndex");
			return result;
		}
		case OMX_ErrorPortUnpopulated:
		{
			result = g_strdup ("Omx.Error.PortUnpopulated");
			return result;
		}
		case OMX_ErrorComponentSuspended:
		{
			result = g_strdup ("Omx.Error.ComponentSuspended");
			return result;
		}
		case OMX_ErrorDynamicResourcesUnavailable:
		{
			result = g_strdup ("Omx.Error.DynamicResourcesUnavailable");
			return result;
		}
		case OMX_ErrorMbErrorsInFrame:
		{
			result = g_strdup ("Omx.Error.MbErrorsInFrame");
			return result;
		}
		case OMX_ErrorFormatNotDetected:
		{
			result = g_strdup ("Omx.Error.FormatNotDetected");
			return result;
		}
		case OMX_ErrorContentPipeOpenFailed:
		{
			result = g_strdup ("Omx.Error.ContentPipeOpenFailed");
			return result;
		}
		case OMX_ErrorContentPipeCreationFailed:
		{
			result = g_strdup ("Omx.Error.ContentPipeCreationFailed");
			return result;
		}
		case OMX_ErrorSeperateTablesUsed:
		{
			result = g_strdup ("Omx.Error.SeperateTablesUsed");
			return result;
		}
		case OMX_ErrorTunnelingUnsupported:
		{
			result = g_strdup ("Omx.Error.TunnelingUnsupported");
			return result;
		}
		default:
		{
			result = g_strdup ("(unknown)");
			return result;
		}
	}
}


static gpointer _g_error_copy0 (gpointer self) {
	return self ? g_error_copy (self) : NULL;
}


static void omx_try_run (OMX_ERRORTYPE err, const char* file, const char* function, gint line, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (file != NULL);
	g_return_if_fail (function != NULL);
	_inner_error_ = NULL;
	if (err != OMX_ErrorNone) {
		char* _tmp0_;
		GError* _tmp1_;
		GError* e;
		e = (_tmp1_ = g_error_new (omx_error_domain (), (gint) err, "%s (0x%x) in function %s at %s:%d\n", _tmp0_ = omx_error_to_string (err), err, function, file, line, NULL), _g_free0 (_tmp0_), _tmp1_);
		_inner_error_ = _g_error_copy0 ((GError*) e);
		{
			g_propagate_error (error, _inner_error_);
			_g_error_free0 (e);
			return;
		}
		_g_error_free0 (e);
	}
}


static void simple_mp3_player_get_handles (SimpleMp3Player* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_GetHandle (&self->priv->audiodec_handle, "OMX.st.audio_decoder.mp3.mad", self, &SIMPLE_MP3_PLAYER_audiodec_callbacks), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_try_run (OMX_GetHandle (&self->priv->audiosink_handle, "OMX.st.alsa.alsasink", self, &SIMPLE_MP3_PLAYER_audiosink_callbacks), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


static void simple_mp3_player_pass_to_idle_and_allocate_buffers (SimpleMp3Player* self, GError** error) {
	GError * _inner_error_;
	OMX_BUFFERHEADERTYPE** _tmp0_;
	OMX_BUFFERHEADERTYPE** _tmp1_;
	OMX_BUFFERHEADERTYPE** _tmp2_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_SendCommand (self->priv->audiodec_handle, OMX_CommandStateSet, (gint) OMX_StateIdle, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_try_run (OMX_SendCommand (self->priv->audiosink_handle, OMX_CommandStateSet, (gint) OMX_StateIdle, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	self->priv->in_buffer_audiodec = (_tmp0_ = g_new0 (OMX_BUFFERHEADERTYPE*, SIMPLE_MP3_PLAYER_n_buffers + 1), self->priv->in_buffer_audiodec = (g_free (self->priv->in_buffer_audiodec), NULL), self->priv->in_buffer_audiodec_length1 = SIMPLE_MP3_PLAYER_n_buffers, self->priv->in_buffer_audiodec_size = self->priv->in_buffer_audiodec_length1, _tmp0_);
	self->priv->out_buffer_audiodec = (_tmp1_ = g_new0 (OMX_BUFFERHEADERTYPE*, SIMPLE_MP3_PLAYER_n_buffers + 1), self->priv->out_buffer_audiodec = (g_free (self->priv->out_buffer_audiodec), NULL), self->priv->out_buffer_audiodec_length1 = SIMPLE_MP3_PLAYER_n_buffers, self->priv->out_buffer_audiodec_size = self->priv->out_buffer_audiodec_length1, _tmp1_);
	self->priv->in_buffer_audiosink = (_tmp2_ = g_new0 (OMX_BUFFERHEADERTYPE*, SIMPLE_MP3_PLAYER_n_buffers + 1), self->priv->in_buffer_audiosink = (g_free (self->priv->in_buffer_audiosink), NULL), self->priv->in_buffer_audiosink_length1 = SIMPLE_MP3_PLAYER_n_buffers, self->priv->in_buffer_audiosink_size = self->priv->in_buffer_audiosink_length1, _tmp2_);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp3_;
			_tmp3_ = TRUE;
			while (TRUE) {
				if (!_tmp3_) {
					i++;
				}
				_tmp3_ = FALSE;
				if (!(i < SIMPLE_MP3_PLAYER_n_buffers)) {
					break;
				}
				omx_try_run (OMX_AllocateBuffer (self->priv->audiodec_handle, &self->priv->in_buffer_audiodec[i], (gint) OMX_DirInput, NULL, (guint) SIMPLE_MP3_PLAYER_buffer_in_size), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
				omx_try_run (OMX_AllocateBuffer (self->priv->audiodec_handle, &self->priv->out_buffer_audiodec[i], (gint) OMX_DirOutput, NULL, (guint) SIMPLE_MP3_PLAYER_buffer_out_size), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
				omx_try_run (OMX_UseBuffer (self->priv->audiosink_handle, &self->priv->in_buffer_audiosink[i], (gint) OMX_DirInput, NULL, (guint) SIMPLE_MP3_PLAYER_buffer_out_size, self->priv->out_buffer_audiodec[i]->pBuffer), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
			}
		}
	}
	tsem_down (&self->priv->audiodec_sem);
	tsem_down (&self->priv->audiosink_sem);
}


static void simple_mp3_player_pass_to_executing (SimpleMp3Player* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_SendCommand (self->priv->audiodec_handle, OMX_CommandStateSet, (gint) OMX_StateExecuting, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_try_run (OMX_SendCommand (self->priv->audiosink_handle, OMX_CommandStateSet, (gint) OMX_StateExecuting, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	tsem_down (&self->priv->audiodec_sem);
	tsem_down (&self->priv->audiosink_sem);
}


static void simple_mp3_player_move_buffers (SimpleMp3Player* self, const char* filename, GError** error) {
	GError * _inner_error_;
	FILE* _tmp0_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	_inner_error_ = NULL;
	self->priv->fd = (_tmp0_ = fopen (filename, "rb"), _fclose0 (self->priv->fd), _tmp0_);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp1_;
			_tmp1_ = TRUE;
			while (TRUE) {
				gsize data_read;
				if (!_tmp1_) {
					i++;
				}
				_tmp1_ = FALSE;
				if (!(i < SIMPLE_MP3_PLAYER_n_buffers)) {
					break;
				}
				data_read = fread (self->priv->in_buffer_audiodec[i]->pBuffer, 1, self->priv->in_buffer_audiodec[i]->nAllocLen, self->priv->fd);
				self->priv->in_buffer_audiodec[i]->nFilledLen = data_read;
				self->priv->in_buffer_audiodec[i]->nOffset = (gsize) 0;
				omx_try_run (OMX_EmptyThisBuffer (self->priv->audiodec_handle, self->priv->in_buffer_audiodec[i]), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
			}
		}
	}
	omx_try_run (OMX_FillThisBuffer (self->priv->audiodec_handle, self->priv->out_buffer_audiodec[0]), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	tsem_down (&self->priv->eos_sem);
}


static void simple_mp3_player_pass_to_idle (SimpleMp3Player* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_SendCommand (self->priv->audiodec_handle, OMX_CommandStateSet, (gint) OMX_StateIdle, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_try_run (OMX_SendCommand (self->priv->audiosink_handle, OMX_CommandStateSet, (gint) OMX_StateIdle, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	tsem_down (&self->priv->audiodec_sem);
	tsem_down (&self->priv->audiosink_sem);
}


static void simple_mp3_player_pass_to_loaded_and_free_buffers (SimpleMp3Player* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_SendCommand (self->priv->audiodec_handle, OMX_CommandStateSet, (gint) OMX_StateLoaded, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_try_run (OMX_SendCommand (self->priv->audiosink_handle, OMX_CommandStateSet, (gint) OMX_StateLoaded, NULL), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				if (!_tmp0_) {
					i++;
				}
				_tmp0_ = FALSE;
				if (!(i < SIMPLE_MP3_PLAYER_n_buffers)) {
					break;
				}
				omx_try_run (OMX_FreeBuffer (self->priv->audiodec_handle, (gint) OMX_DirInput, self->priv->in_buffer_audiodec[i]), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
				omx_try_run (OMX_FreeBuffer (self->priv->audiodec_handle, (gint) OMX_DirOutput, self->priv->out_buffer_audiodec[i]), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
				omx_try_run (OMX_FreeBuffer (self->priv->audiosink_handle, (gint) OMX_DirInput, self->priv->in_buffer_audiosink[i]), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
				if (_inner_error_ != NULL) {
					g_propagate_error (error, _inner_error_);
					return;
				}
			}
		}
	}
	tsem_down (&self->priv->audiodec_sem);
	tsem_down (&self->priv->audiosink_sem);
}


static void simple_mp3_player_free_handles (SimpleMp3Player* self, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_FreeHandle (self->priv->audiodec_handle), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_try_run (OMX_FreeHandle (self->priv->audiosink_handle), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


void simple_mp3_player_decode (SimpleMp3Player* self, const char* filename, GError** error) {
	GError * _inner_error_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (filename != NULL);
	_inner_error_ = NULL;
	omx_try_run (OMX_Init (), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	simple_mp3_player_get_handles (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	simple_mp3_player_pass_to_idle_and_allocate_buffers (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	simple_mp3_player_pass_to_executing (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	simple_mp3_player_move_buffers (self, filename, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	simple_mp3_player_pass_to_idle (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	simple_mp3_player_pass_to_loaded_and_free_buffers (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	simple_mp3_player_free_handles (self, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
	omx_try_run (OMX_Deinit (), __FILE__, __FUNCTION__, __LINE__, &_inner_error_);
	if (_inner_error_ != NULL) {
		g_propagate_error (error, _inner_error_);
		return;
	}
}


SimpleMp3Player* simple_mp3_player_construct (GType object_type) {
	SimpleMp3Player * self;
	self = g_object_newv (object_type, 0, NULL);
	return self;
}


SimpleMp3Player* simple_mp3_player_new (void) {
	return simple_mp3_player_construct (TYPE_SIMPLE_MP3_PLAYER);
}


static GObject * simple_mp3_player_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	SimpleMp3Player * self;
	parent_class = G_OBJECT_CLASS (simple_mp3_player_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = SIMPLE_MP3_PLAYER (obj);
	{
		tsem_init (&self->priv->audiodec_sem, (guint) 0);
		tsem_init (&self->priv->audiosink_sem, (guint) 0);
		tsem_init (&self->priv->eos_sem, (guint) 0);
	}
	return obj;
}


static void simple_mp3_player_class_init (SimpleMp3PlayerClass * klass) {
	simple_mp3_player_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SimpleMp3PlayerPrivate));
	G_OBJECT_CLASS (klass)->constructor = simple_mp3_player_constructor;
	G_OBJECT_CLASS (klass)->finalize = simple_mp3_player_finalize;
}


static void simple_mp3_player_instance_init (SimpleMp3Player * self) {
	self->priv = SIMPLE_MP3_PLAYER_GET_PRIVATE (self);
}


static void simple_mp3_player_finalize (GObject* obj) {
	SimpleMp3Player * self;
	self = SIMPLE_MP3_PLAYER (obj);
	self->priv->in_buffer_audiosink = (g_free (self->priv->in_buffer_audiosink), NULL);
	self->priv->in_buffer_audiodec = (g_free (self->priv->in_buffer_audiodec), NULL);
	self->priv->out_buffer_audiodec = (g_free (self->priv->out_buffer_audiodec), NULL);
	_fclose0 (self->priv->fd);
	G_OBJECT_CLASS (simple_mp3_player_parent_class)->finalize (obj);
}


GType simple_mp3_player_get_type (void) {
	static GType simple_mp3_player_type_id = 0;
	if (simple_mp3_player_type_id == 0) {
		static const GTypeInfo g_define_type_info = { sizeof (SimpleMp3PlayerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) simple_mp3_player_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SimpleMp3Player), 0, (GInstanceInitFunc) simple_mp3_player_instance_init, NULL };
		simple_mp3_player_type_id = g_type_register_static (G_TYPE_OBJECT, "SimpleMp3Player", &g_define_type_info, 0);
	}
	return simple_mp3_player_type_id;
}


gint _main (char** args, int args_length1) {
	gint result;
	GError * _inner_error_;
	SimpleMp3Player* decoder;
	_inner_error_ = NULL;
	if (args_length1 != 2) {
		g_print ("%s <file.mp3>\n", args[0]);
		result = 1;
		return result;
	}
	decoder = simple_mp3_player_new ();
	{
		simple_mp3_player_decode (decoder, args[1], &_inner_error_);
		if (_inner_error_ != NULL) {
			goto __catch0_g_error;
		}
		result = 0;
		_g_object_unref0 (decoder);
		return result;
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
			g_print ("%s", e->message);
			result = 1;
			_g_error_free0 (e);
			_g_object_unref0 (decoder);
			return result;
		}
	}
	__finally0:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (decoder);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_g_object_unref0 (decoder);
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _main (argv, argc);
}




